/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Model/Donot.glb --types --printwidth 120 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Donut_Cartoon: THREE.Mesh
    Front: THREE.Mesh
    Body: THREE.Mesh
  }
  materials: {
    Donut_Material: THREE.MeshPhysicalMaterial
    Mat_Front: THREE.MeshStandardMaterial
    Mat_Body: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/Donot.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Donut_Cartoon.geometry} material={materials.Donut_Material} />
      <mesh geometry={nodes.Front.geometry} material={materials.Mat_Front} />
      <mesh geometry={nodes.Body.geometry} material={materials.Mat_Body} />
    </group>
  )
}

useGLTF.preload('/Donot.glb')
