import { Users, Video, Zap, Globe, Box, Building, Package, ShoppingCart } from "lucide-react"

export const services = [
  {
    id: "influencer",
    icon: Users,
    title: "Influencer Marketing",
    tagline: "Connect with Creators, Amplify Your Brand",
    description: "Strategic influencer partnerships that deliver measurable ROI and authentic brand connections",
    features: [
      "Creator matchmaking & vetting",
      "Campaign strategy & execution",
      "Performance tracking & analytics",
      "Contract management",
      "Content rights management",
    ],
    benefits: "Average 3.5x ROI on influencer campaigns",
    color: "from-purple-500 to-pink-500",
    image: "/services/service_influencer_1769254567416.png",
    price: "₹25,000",
  },
  {
    id: "video",
    icon: Video,
    title: "Video Editing",
    tagline: "Professional Post-Production Excellence",
    description: "Transform raw footage into compelling visual stories that captivate and convert",
    features: [
      "Commercial & corporate videos",
      "Social media content optimization",
      "Motion graphics & VFX",
      "Color grading & audio mixing",
      "Multi-platform formatting",
    ],
    benefits: "Delivered 10,000+ hours of edited content",
    color: "from-blue-500 to-cyan-500",
    image: "/services/service_video_editing_1769254583423.png",
    price: "₹5,000",
  },
  {
    id: "ai",
    icon: Zap,
    title: "AI Automation",
    tagline: "Intelligent Workflows, Maximum Efficiency",
    description: "Leverage cutting-edge AI to streamline operations and unlock new possibilities",
    features: [
      "Custom chatbot development",
      "Workflow automation",
      "Predictive analytics",
      "Natural language processing",
      "Computer vision solutions",
    ],
    benefits: "Reduce operational costs by up to 60%",
    color: "from-yellow-500 to-orange-500",
    image: "/services/service_ai_automation_1769254601186.png",
    price: "₹30,000",
  },
  {
    id: "web",
    icon: Globe,
    title: "Website Building",
    tagline: "Custom Web Solutions That Convert",
    description: "Beautiful, fast, and scalable websites built with modern technologies",
    features: [
      "Custom CMS development",
      "E-commerce platforms",
      "Progressive Web Apps",
      "API integrations",
      "Performance optimization",
    ],
    benefits: "99.9% uptime across all client sites",
    color: "from-green-500 to-emerald-500",
    image: "/services/service_web_dev_1769254617586.png",
    price: "₹15,000",
  },
  {
    id: "3d-ads",
    icon: Box,
    title: "3D Ads Generation",
    tagline: "Immersive Advertising Experiences",
    description: "Stand out with stunning 3D advertisements that capture attention and drive engagement",
    features: [
      "3D product visualization",
      "Interactive ad campaigns",
      "AR/VR ready content",
      "Cross-platform compatibility",
      "Real-time rendering",
    ],
    benefits: "250% higher engagement vs traditional ads",
    color: "from-red-500 to-rose-500",
    image: "/services/service_3d_ads_1769254643486.png",
    price: "₹20,000",
  },
  {
    id: "3d-real-estate",
    icon: Building,
    title: "3D Real Estate",
    tagline: "Virtual Tours That Sell Properties",
    description: "Bring properties to life with photorealistic 3D visualization and virtual tours",
    features: [
      "Interactive virtual tours",
      "Photorealistic rendering",
      "VR walkthroughs",
      "Floor plan visualization",
      "Day/night lighting scenarios",
    ],
    benefits: "Reduce time-to-sale by 40%",
    color: "from-indigo-500 to-purple-500",
    image: "/services/service_3d_real_estate_1769254659892.png",
    price: "₹45,000",
  },
  {
    id: "3d-mockups",
    icon: Package,
    title: "3D Mockups",
    tagline: "Product Visualization Perfected",
    description: "Showcase products in stunning detail before they're even manufactured",
    features: [
      "Photorealistic product renders",
      "Material & texture simulation",
      "Dynamic lighting setups",
      "Multiple angle variations",
      "Quick iteration cycles",
    ],
    benefits: "75% faster product approval process",
    color: "from-teal-500 to-cyan-500",
    image: "/services/service_3d_mockups_1769254678174.png",
    price: "₹10,000",
  },
  {
    id: "3d-configurator",
    icon: ShoppingCart,
    title: "3D Product Configurator",
    tagline: "Interactive Shopping Experiences",
    description: "Let customers customize products in real-time with seamless Shopify integration",
    features: [
      "Real-time product customization",
      "Shopify & WooCommerce integration",
      "Mobile-optimized 3D viewer",
      "Color & material options",
      "Cart integration",
    ],
    benefits: "Increase conversion rates by 65%",
    color: "from-pink-500 to-rose-500",
    image: "/services/service_3d_configurator_1769254692497.png",
    price: "₹55,000",
  },
]
